# Generated by Django 4.2.30 on 2026-08-30 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='优惠券名称')),
                ('discount_type', models.CharField(choices=[('fixed', '满减券'), ('discount', '折扣券')], default='fixed', max_length=20, verbose_name='优惠类型')),
                ('value', models.DecimalField(decimal_places=2, help_text='满减券填写抵扣金额(元)；折扣券填写折扣（如 8.5 表示 85 折）', max_digits=10, verbose_name='面额/折扣')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, help_text='订单应付租金满该金额可用，0 表示无门槛', max_digits=10, verbose_name='使用门槛(元)')),
                ('total_count', models.PositiveIntegerField(default=100, verbose_name='发行总量')),
                ('claimed_count', models.PositiveIntegerField(default=0, verbose_name='已领取数量')),
                ('start_date', models.DateField(verbose_name='生效日期')),
                ('end_date', models.DateField(verbose_name='失效日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '优惠券',
                'db_table': 't_coupon',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额(元)')),
                ('payment_type', models.CharField(choices=[('rent', '租金'), ('deposit', '押金'), ('fine', '违约金'), ('deposit_refund', '押金退还'), ('rent_refund', '租金退款')], max_length=20, verbose_name='类型')),
                ('method', models.CharField(default='模拟支付', max_length=50, verbose_name='支付/退款方式')),
                ('status', models.CharField(default='success', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '支付流水',
                'db_table': 't_payment',
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, null=True, verbose_name='使用订单ID')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('claimed_at', models.DateTimeField(auto_now_add=True, verbose_name='领取时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='payments.coupon', verbose_name='优惠券模板')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户优惠券',
                'db_table': 't_user_coupon',
                'unique_together': {('user', 'coupon')},
            },
        ),
    ]
