# Generated by Django 4.2.30 on 2026-08-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('holiday', '节假日上浮'), ('weekend', '周末上浮'), ('peak', '旺季调价'), ('off_season', '淡季促销'), ('early_bird', '早鸟优惠'), ('long_rent', '长租优惠')], max_length=30, unique=True, verbose_name='规则类型')),
                ('name', models.CharField(max_length=50, verbose_name='规则名称')),
                ('factor', models.DecimalField(decimal_places=2, help_text='上浮为正数（如 0.30 表示 +30%），优惠为负数（如 -0.15 表示 -15%）', max_digits=5, verbose_name='调整系数')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='规则说明')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '定价规则',
                'db_table': 't_price_rule',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='参数键')),
                ('value', models.CharField(max_length=100, verbose_name='参数值')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='参数说明')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统设置',
                'db_table': 't_system_setting',
            },
        ),
    ]
