# Generated by Django 4.2.30 on 2026-08-30 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='1-5 星', verbose_name='评分')),
                ('content', models.TextField(blank=True, verbose_name='评价内容')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.order', verbose_name='关联订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='评价用户')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vehicles.vehicle', verbose_name='被评车辆')),
            ],
            options={
                'verbose_name': '车辆评价',
                'db_table': 't_review',
            },
        ),
    ]
