# Generated by Django 4.2.30 on 2026-08-30 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='品牌名称')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='品牌LOGO')),
                ('description', models.TextField(blank=True, verbose_name='品牌简介')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '品牌',
                'db_table': 't_brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '车辆分类',
                'db_table': 't_category',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='型号')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='车牌号')),
                ('color', models.CharField(default='白色', max_length=20, verbose_name='颜色')),
                ('seats', models.PositiveSmallIntegerField(default=5, verbose_name='座位数')),
                ('displacement', models.CharField(blank=True, default='', max_length=20, verbose_name='排量')),
                ('fuel_type', models.CharField(choices=[('gasoline', '汽油'), ('diesel', '柴油'), ('electric', '纯电动'), ('hybrid', '混动')], default='gasoline', max_length=20, verbose_name='燃油类型')),
                ('daily_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='日租金(元)')),
                ('status', models.CharField(choices=[('available', '可租'), ('renting', '租赁中'), ('off_shelf', '已下架')], default='available', max_length=20, verbose_name='状态')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='封面图')),
                ('description', models.TextField(blank=True, verbose_name='车辆描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicles.brand', verbose_name='品牌')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicles.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '车辆',
                'db_table': 't_vehicle',
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/', verbose_name='图片')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.vehicle', verbose_name='车辆')),
            ],
            options={
                'verbose_name': '车辆图片',
                'db_table': 't_vehicle_image',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
