# Generated by Django 4.2.30 on 2026-09-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleimage',
            options={'ordering': ['-is_cover', 'sort_order', 'id'], 'verbose_name': '车辆图片'},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='is_cover',
            field=models.BooleanField(default=False, verbose_name='是否封面'),
        ),
    ]
