# Generated by Django 4.2.30 on 2026-09-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicleimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleimage',
            options={'ordering': ['-is_cover', 'id'], 'verbose_name': '车辆图片'},
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='is_cover',
            field=models.BooleanField(default=False, verbose_name='是否主图'),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='上传序号'),
        ),
    ]
