# Generated by Django 4.2.30 on 2026-08-30 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='订单号')),
                ('start_date', models.DateField(verbose_name='取车日期')),
                ('end_date', models.DateField(verbose_name='还车日期')),
                ('days', models.PositiveIntegerField(verbose_name='租期(天)')),
                ('pickup_location', models.CharField(max_length=100, verbose_name='取车地点')),
                ('return_location', models.CharField(max_length=100, verbose_name='还车地点')),
                ('base_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='原价租金(元)')),
                ('dynamic_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='动态租金(元)')),
                ('coupon_id', models.IntegerField(blank=True, null=True, verbose_name='优惠券ID')),
                ('coupon_name', models.CharField(blank=True, default='', max_length=50, verbose_name='优惠券名称')),
                ('coupon_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='优惠券抵扣(元)')),
                ('payable_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='应付租金(元)')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='押金(元)')),
                ('fine', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='违约金(元)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='应付总额(元)')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('renting', '租赁中'), ('to_return', '待还车'), ('completed', '已完成'), ('cancelled', '已取消'), ('overdue', '已逾期'), ('abnormal', '异常处理')], default='pending', max_length=20, verbose_name='订单状态')),
                ('is_overdue', models.BooleanField(default=False, verbose_name='是否逾期')),
                ('deposit_returned', models.BooleanField(default=False, verbose_name='押金是否已退还')),
                ('extend_to_date', models.DateField(blank=True, null=True, verbose_name='续租目标还车日期')),
                ('extension_status', models.CharField(choices=[('none', '无'), ('pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回')], default='none', max_length=20, verbose_name='续租审批状态')),
                ('extend_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='续租增加租金(元)')),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=200, verbose_name='取消原因')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('pickup_at', models.DateTimeField(blank=True, null=True, verbose_name='取车时间')),
                ('return_at', models.DateTimeField(blank=True, null=True, verbose_name='确认还车时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='下单用户')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='vehicles.vehicle', verbose_name='租赁车辆')),
            ],
            options={
                'verbose_name': '租赁订单',
                'db_table': 't_order',
            },
        ),
    ]
